### PR TITLE
Add section on thread synchronization

### PR DESCRIPTION
**Pull request by HadrienG2**
As promised, this is my attempt to give a summary of all the things that can go wrong when using unsafe code to synchronize threads.

### CODE REVIEW

**Comment by HadrienG2** [comment]
It might be a good idea to also add a section about premature deallocation of shared resources used by other threads, which is another _classic_ multi-threading gotcha. But I'm not sure if I can find a nice Correct/Incorrect example pair for this.

Usually, people go for custom resource management because they're in a hot code path where `Arc`-style atomic increment/decrement is too expensive, and there is no general suggestion that can apply to all use cases there...

**Comment by HadrienG2** [comment]
PS: I believe I am not responsible for this CI failure. Should I fix it anyway?

**Comment by ExpHP** [comment]
Don't worry about the CI failure, it's my fault for not checking that the Travis config works after setting it up =P.  (I got distracted trying to figure out how to deploy to a GitHub pages)

**Comment by ExpHP** [comment]
Looks great!

**Pull request merged**
